[versions]
# Android versions
minSdk = "24"
targetSdk = "36"
compileSdk = "36"
buildTools = "36.0.0"
# Dependencies versions
agp = "8.11.0"
fresco = "3.6.0"
apollo = "4.3.3"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
fresco-middleware = { module = "com.facebook.fresco:middleware", version.ref = "fresco" }
fresco-animated-gif  = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
fresco-animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
fresco-webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }

apollo =  { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-cache = { module = "com.apollographql.apollo:apollo-cache-normalized", version.ref = "apollo" }
apollo-gradle = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
