name: Android Instrumentation Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - .github/workflows/android-instrumentation-tests.yml
      - apps/expo-go/android/**
      - fastlane/**
      # - packages/**/android/**
      - packages/expo-eas-client/android/**
      - packages/expo-json-utils/android/**
      - packages/expo-manifests/android/**
      - packages/expo-notifications/android/**
      - packages/expo-updates/android/**
      - tools/src/commands/AndroidNativeUnitTests.ts
      - yarn.lock
      - '!packages/@expo/cli/**'
  pull_request:
    paths:
      - .github/workflows/android-instrumentation-tests.yml
      - apps/expo-go/android/**
      - fastlane/**
      # - packages/**/android/**
      - packages/expo-eas-client/android/**
      - packages/expo-json-utils/android/**
      - packages/expo-manifests/android/**
      - packages/expo-notifications/android/**
      - packages/expo-updates/android/**
      - tools/src/commands/AndroidNativeUnitTests.ts
      - yarn.lock
      - '!packages/@expo/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 150
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
    strategy:
      matrix:
        api-level: [34]
    steps:
      - name: â¬¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ðŸ‘€ Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: ðŸ§¹ Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: ðŸ”¨ Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: 'true'
          yarn-workspace: 'true'
          yarn-tools: 'true'
          react-native-gradle-downloads: 'true'
      - name: âž• Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ðŸ§¶ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ðŸ“± Run instrumented unit tests
        timeout-minutes: 80
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: expotools android-native-unit-tests --type instrumented
      - name: ðŸ’¾ Save test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: packages/**/build/outputs/androidTest-results/**/*
