name: Android Unit Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - .github/workflows/android-unit-tests.yml
      - android/**
      - fastlane/**
      - packages/**/android/**
      - tools/**
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/android-unit-tests.yml
      - android/**
      - fastlane/**
      - packages/**/android/**
      - tools/**
      - yarn.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
    steps:
      - name: â¬¢ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - name: ðŸ‘€ Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: ðŸ”¨ Use JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: â™»ï¸ Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: â™»ï¸ Restore yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: ðŸ§¶ Install node modules in root dir
        run: yarn install --frozen-lockfile
      - name: â™»ï¸ Restore node modules in tools
        uses: actions/cache@v2
        with:
          path: tools/node_modules
          key: ${{ runner.os }}-tools-modules-${{ hashFiles('tools/yarn.lock') }}
      - name: â™»ï¸ Restore Gradle caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: Run Spotless lint check
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/21.4.7075529/
        working-directory: android
        run: ./gradlew spotlessCheck || { echo '::error Spotless lint failed. Run `./gradlew spotlessApply` to automatically fix formatting.' && exit 1; }
      - name: ðŸŽ¸ Run native Android unit tests
        timeout-minutes: 30
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/21.4.7075529/
        run: expotools native-unit-tests --platform android
      - name: ðŸŽ¸ Run instrumented unit tests
        timeout-minutes: 40
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot-save
          script: |
            # wait for emulator to be fully boot up
            sleep 60
            bin/expotools android-native-unit-tests --type instrumented
      - name: ðŸ’¿ Save test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: packages/**/build/test-results/**/*xml
