name: Brownfield Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/brownfield.yml
      - packages/expo-brownfield/**
      - packages/expo/**
      - packages/expo-router/**
      - packages/expo-dev-menu/**
      - packages/expo-manifests/**
      - packages/expo-updates/**
      - yarn.lock
      - '!**.md'
  pull_request:
    paths:
      - .github/workflows/brownfield.yml
      - packages/expo-brownfield/**
      - packages/expo/**
      - packages/expo-router/**
      - packages/expo-dev-menu/**
      - packages/expo-manifests/**
      - packages/expo-updates/**
      - yarn.lock
      - '!**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-changes:
    runs-on: ubuntu-24.04
    outputs:
      all_tests: ${{ steps.filter.outputs.all_tests }}
      cli_e2e: ${{ steps.filter.outputs.cli_e2e }}
      plugin_e2e: ${{ steps.filter.outputs.plugin_e2e }}
      compilation_test_android: ${{ steps.filter.outputs.compilation_test_android }}
      compilation_test_ios: ${{ steps.filter.outputs.compilation_test_ios }}
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        # TODO(pmleczek): Update paths once we wrap up Maestro tests (remove expo-brownfield/**)
        # TODO(pmleczek): Refine paths like expo/**, expo-router/**, etc. (?)
        # TODO(pmleczek): Add "- 'packages/expo-updates/**'" to the compilation test filters
        with:
          filters: |
            all_tests: 
              - '.github/workflows/brownfield.yml'
              - 'yarn.lock'
            cli_e2e:
              - 'packages/expo-brownfield/bin/**'
              - 'packages/expo-brownfield/cli/**'
              - 'packages/expo-brownfield/e2e/cli/**'
              - 'packages/expo-brownfield/e2e/utils/**'
              - 'packages/expo-brownfield/package.json'
            plugin_e2e:
              - 'packages/expo-brownfield/plugin/**'
              - 'packages/expo-brownfield/e2e/plugin/**'
              - 'packages/expo-brownfield/e2e/utils/**'
              - 'packages/expo-brownfield/app.plugin.js'
              - 'packages/expo-brownfield/package.json'
            compilation_test_android:
              - 'packages/expo-brownfield/**'
              - 'packages/expo/**'
              - 'packages/expo-router/**'
              - 'packages/expo-dev-menu/**'
              - 'packages/expo-manifests/**'
            compilation_test_ios:
              - 'packages/expo-brownfield/**'
              - 'packages/expo/**'
              - 'packages/expo-router/**'
              - 'packages/expo-dev-menu/**'
              - 'packages/expo-manifests/**'

  jest-ubuntu-cli:
    runs-on: ubuntu-24.04
    needs: analyze-changes
    if: needs.analyze-changes.outputs.cli_e2e == 'true' || needs.analyze-changes.outputs.all_tests == 'true'
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    steps:
      - name: üèóÔ∏è Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üèóÔ∏è Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest

      - name: üëÄ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: ‚¨áÔ∏è Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

      - name: üîé Find Yarn Cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: ‚ôªÔ∏è Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: üß∂ Install node modules in root dir
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          YARN_IGNORE_SCRIPTS: 'true'

      - name: üë∑ Build Expo CLI
        run: yarn workspace @expo/cli prepare

      - name: üë∑ Build Create Expo CLI
        run: yarn workspace create-expo build:prod

      - name: üë∑ Build Expo Brownfield
        run: yarn workspace expo-brownfield prepare

      - name: üì¶ Generate expo-brownfield tarball
        run: npm pack --json
        working-directory: packages/expo-brownfield

      - name: üì¶ Generate expo-template-default tarball
        run: npm pack --json
        working-directory: templates/expo-template-default

      - name: üß™ E2E Test Brownfield CLI
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-cli --testPathIgnorePatterns e2e/cli/__tests__/build-ios.test.ts --max-workers 1 --shard ${{ matrix.shard }}/${{ strategy.job-total }}

      - name: üß™ E2E Test Brownfield Config Plugin
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-plugin --testPathIgnorePatterns e2e/plugin/__tests__/plugin-ios.test.ts --max-workers 1 --shard ${{ matrix.shard }}/${{ strategy.job-total }} --passWithNoTests

  jest-macos-cli:
    runs-on: macos-15
    needs: analyze-changes
    if: needs.analyze-changes.outputs.cli_e2e == 'true' || needs.analyze-changes.outputs.all_tests == 'true'
    steps:
      - name: üèóÔ∏è Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üèóÔ∏è Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest

      - name: üíé Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: üíé Install cocoapods
        run: sudo gem install cocoapods

      - name: üëÄ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: ‚¨áÔ∏è Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

      - name: üîé Find Yarn Cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: ‚ôªÔ∏è Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: üß∂ Install node modules in root dir
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          YARN_IGNORE_SCRIPTS: 'true'

      - name: üë∑ Build Expo CLI
        run: yarn workspace @expo/cli prepare

      - name: üë∑ Build Create Expo CLI
        run: yarn workspace create-expo build:prod

      - name: üë∑ Build Expo Brownfield
        run: yarn workspace expo-brownfield prepare

      - name: üì¶ Generate expo-brownfield tarball
        run: npm pack --json
        working-directory: packages/expo-brownfield

      - name: üì¶ Generate expo-template-default tarball
        run: npm pack --json
        working-directory: templates/expo-template-default

      - name: üß™ E2E Test Brownfield CLI
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-cli e2e/cli/__tests__/build-ios.test.ts

      - name: üß™ E2E Test Brownfield Config Plugin
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-plugin e2e/plugin/__tests__/plugin-ios.test.ts

  compilation-test-android:
    runs-on: ubuntu-24.04
    needs: analyze-changes
    if: needs.analyze-changes.outputs.compilation_test_android == 'true' || needs.analyze-changes.outputs.all_tests == 'true'
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v5
      - name: üßπ Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: üèóÔ∏è Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: üî® Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: ‚ûï Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ‚ôªÔ∏è Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: 'true'
          yarn-workspace: 'true'
          yarn-tools: 'true'
          react-native-gradle-downloads: 'true'
      - name: üß∂ Install workspace node modules
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ü§ñ Build and publish Android brownfield artifacts
        run: |
          npx expo prebuild --clean -p android
          npx expo-brownfield build:android --repo MavenLocal --all --verbose
        working-directory: apps/brownfield-tester/expo-app
      - name: üîî Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_android }}
          channel: '#expo-android'
          author_name: expo-brownfield Compilation Test (Android)

  compilation-test-ios:
    runs-on: macos-15
    needs: analyze-changes
    if: needs.analyze-changes.outputs.compilation_test_ios == 'true' || needs.analyze-changes.outputs.all_tests == 'true'
    strategy:
      fail-fast: true
      matrix:
        build-type: [debug, release]
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v5
      - name: üî® Switch to Xcode 26.0
        run: sudo xcode-select --switch /Applications/Xcode_26.0.app
      - name: ‚ûï Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: üíé Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      - name: ‚ôªÔ∏è Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
          yarn-tools: 'true'
      - name: üß∂ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: üçè Build iOS artifacts
        run: |
          npx expo prebuild --clean --platform ios
          npx expo-brownfield build-ios --${{ matrix.build-type }} --verbose
        working-directory: apps/brownfield-tester/expo-app
      - name: üîî Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_ios }}
          channel: '#expo-ios'
          author_name: expo-brownfield Compilation Test (iOS)
