name: Brownfield E2E Tests (CLI + Plugin)

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/brownfield.yml
      - packages/expo-brownfield/**
      - yarn.lock
      - '!**.md'
  pull_request:
    paths:
      - .github/workflows/brownfield.yml
      - packages/expo-brownfield/**
      - yarn.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-changes:
    runs-on: ubuntu-24.04
    outputs:
      cli_e2e: ${{ steps.filter.outputs.cli_e2e }}
      plugin_e2e: ${{ steps.filter.outputs.plugin_e2e }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        # TODO(pmleczek): Update paths once we wrap up Maestro tests
        # TODO(pmleczek): Refine paths like expo/**, expo-router/**, etc.
        # TODO(pmleczek): Add "- 'packages/expo-updates/**'" to the compilation test filters
        with:
          filters: |
            cli_e2e:
              - '.github/workflows/brownfield.yml'
              - 'packages/expo-brownfield/bin/**'
              - 'packages/expo-brownfield/cli/**'
              - 'packages/expo-brownfield/e2e/cli/**'
              - 'packages/expo-brownfield/e2e/utils/**'
              - 'packages/expo-brownfield/package.json'
            plugin_e2e:
              - '.github/workflows/brownfield.yml'
              - 'packages/expo-brownfield/plugin/**'
              - 'packages/expo-brownfield/e2e/plugin/**'
              - 'packages/expo-brownfield/e2e/utils/**'
              - 'packages/expo-brownfield/app.plugin.js'
              - 'packages/expo-brownfield/package.json'
            compilation_test:
              - '.github/workflows/brownfield.yml'
              - 'packages/expo-brownfield/**'
              - 'packages/expo/**'
              - 'packages/expo-router/**'
              - 'packages/expo-dev-menu/**'
              - 'packages/expo-manifests/**'

  jest-ubuntu-cli:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    steps:
      - name: ğŸ—ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest

      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: â¬‡ï¸ Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

      - name: ğŸ” Find Yarn Cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: â™»ï¸ Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ§¶ Install node modules in root dir
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          YARN_IGNORE_SCRIPTS: 'true'

      - name: ğŸ‘· Build Expo CLI
        run: yarn workspace @expo/cli prepare

      - name: ğŸ‘· Build Create Expo CLI
        run: yarn workspace create-expo build:prod

      - name: ğŸ‘· Build Expo Brownfield
        run: yarn workspace expo-brownfield prepare

      - name: ğŸ“¦ Generate expo-brownfield tarball
        run: npm pack --json
        working-directory: packages/expo-brownfield

      - name: ğŸ“¦ Generate expo-template-default tarball
        run: npm pack --json
        working-directory: templates/expo-template-default

      - name: ğŸ§ª E2E Test Brownfield CLI
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-cli --testPathIgnorePatterns e2e/cli/__tests__/build-ios.test.ts --max-workers 1 --shard ${{ matrix.shard }}/${{ strategy.job-total }}

      - name: ğŸ§ª E2E Test Brownfield Config Plugin
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-plugin --testPathIgnorePatterns e2e/plugin/__tests__/plugin-ios.test.ts --max-workers 1 --shard ${{ matrix.shard }}/${{ strategy.job-total }} --passWithNoTests

  jest-macos-cli:
    runs-on: macos-15
    steps:
      - name: ğŸ—ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest

      - name: ğŸ’ Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: ğŸ’ Install cocoapods
        run: sudo gem install cocoapods

      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: â¬‡ï¸ Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

      - name: ğŸ” Find Yarn Cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        shell: bash
      - name: â™»ï¸ Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ§¶ Install node modules in root dir
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          YARN_IGNORE_SCRIPTS: 'true'

      - name: ğŸ‘· Build Expo CLI
        run: yarn workspace @expo/cli prepare

      - name: ğŸ‘· Build Create Expo CLI
        run: yarn workspace create-expo build:prod

      - name: ğŸ‘· Build Expo Brownfield
        run: yarn workspace expo-brownfield prepare

      - name: ğŸ“¦ Generate expo-brownfield tarball
        run: npm pack --json
        working-directory: packages/expo-brownfield

      - name: ğŸ“¦ Generate expo-template-default tarball
        run: npm pack --json
        working-directory: templates/expo-template-default

      - name: ğŸ§ª E2E Test Brownfield CLI
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-cli e2e/cli/__tests__/build-ios.test.ts

      - name: ğŸ§ª E2E Test Brownfield Config Plugin
        working-directory: packages/expo-brownfield
        run: yarn test:e2e-plugin e2e/plugin/__tests__/plugin-ios.test.ts

  # TODO(pmleczek): Implement
  # compile
