name: Comments on GitHub issues

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Serialized and escaped JSON describing what and where to comment.'
        required: true

jobs:
  comment:
    runs-on: ubuntu-22.04
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v3
      - name: ðŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x
      - name: âž• Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ðŸ’¬ Comment on GitHub issues as github-actions bot
        run: expotools commentator --payload "${{ github.event.inputs.payload }}"
        env:
          GITHUB_TOKEN: ${{ secrets.EXPO_BOT_GITHUB_TOKEN }}
