name: Docs Website PR Destroy Preview

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-pr.yml'
      - '.github/workflows/docs-pr-destroy.yml'
    types: [closed, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-pr-destroy:
    if: (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview')) ||
        (github.event.action == 'unlabeled' && github.event.label.name == 'preview')
    runs-on: ubuntu-22.04
    steps:
      - name: ðŸª£ Delete docs preview bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: aws s3 rb s3://docs.expo.dev-pr-${{ github.event.pull_request.number }} --force && exit 0
