name: Docs Website PR Destroy Preview

defaults:
  run:
    shell: bash

on:
  pull_request:
    types: [closed, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-pr-destroy:
    if: (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview')) ||
        (github.event.action == 'unlabeled' && github.event.label.name == 'preview')
    runs-on: ubuntu-24.04
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v6
      - name: â¬¢ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: ðŸ§¹ Delete preview deployments
        working-directory: docs
        env:
          CLOUDFLARE_PAGES_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: node scripts/prune-cloudflare-deployments.mjs --project=expo-docs --branch=pr-${{ github.event.pull_request.number }} --keep=0
