name: Expotools

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/expotools.yml
      - tools/**
  pull_request:
    paths:
      - .github/workflows/expotools.yml
      - tools/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: â¬¢ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x

      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches

      - name: ğŸ§¶ Install modules in tools dir
        if: steps.expo-caches.outputs.yarn-tools-hit != 'true'
        run: bun install --yarn --ignore-scripts --frozen-lockfile
        working-directory: tools

      - name: ğŸ›  Compile TypeScript sources
        run: bun run build
        working-directory: tools

      - name: ğŸ›  Typecheck sources
        run: bun run typecheck
        working-directory: tools

      - name: ğŸš¨ Lint TypeScript sources
        run: bun run lint --max-warnings 0
        working-directory: tools
