name: Expotools

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/expotools.yml
      - tools/**
  pull_request:
    paths:
      - .github/workflows/expotools.yml
      - tools/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v4
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-tools: 'true'
      - name: ğŸ§¶ Install modules in tools dir
        if: steps.expo-caches.outputs.yarn-tools-hit != 'true'
        run: yarn install --ignore-scripts --frozen-lockfile
        working-directory: tools
      - name: ğŸ›  Compile TypeScript sources
        run: yarn build
        working-directory: tools
      - name: ğŸ›  Typecheck sources
        run: yarn tsc --noEmit
        working-directory: tools
      - name: ğŸš¨ Lint TypeScript sources
        run: yarn lint --max-warnings 0
        working-directory: tools
