name: Home app

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/home.yml
      - apps/expo-go/**
      - react-native-lab/**
      - pnpm-lock.yaml
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/home.yml
      - apps/expo-go/**
      - react-native-lab/**
      - pnpm-lock.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: ðŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: â¬¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ðŸ§¶ Install node modules
        run: pnpm install --frozen-lockfile

      - name: ðŸ§¶ Yarn install (react-native-lab)
        run: yarn install --frozen-lockfile
        working-directory: react-native-lab/react-native

      - name: ðŸ›  Compile Home sources
        run: pnpm tsc
        working-directory: apps/expo-go

      - name: ðŸ§ª Run Home tests
        run: pnpm jest --maxWorkers 1
        working-directory: apps/expo-go

      - name: ðŸš¨ Lint Home app
        run: pnpm lint --max-warnings 0
        working-directory: apps/expo-go

      - name: ðŸ‘· Build Home app
        run: pnpm expo export
        working-directory: apps/expo-go

      - name: ðŸ”” Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_api }}
          author_name: Home app
