name: Process when issue is closed

on:
  issues:
    types: [closed]

jobs:
  run-on-issue-accepted:
    runs-on: ubuntu-22.04
    if: contains(github.event.issue.labels.*.name, 'Issue accepted')
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v3
      - name: ðŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x
      - name: âž• Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ðŸ”Ž Close Linear issue
        run: expotools close-linear-issue-from-github --issue "${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.EXPO_BOT_GITHUB_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
