name: Process when issue is closed

on:
  issues:
    types: [closed]

jobs:
  run-on-issue-accepted:
    runs-on: ubuntu-22.04
    if: contains(github.event.issue.labels.*.name, 'Issue accepted')
    steps:
      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v3
      - name: ğŸ—ï¸ Setup Expo Tools
        uses: ./.github/actions/setup-expo-tools
      - name: ğŸ” Close Linear issue
        run: expotools close-linear-issue-from-github --issue "${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.EXPO_BOT_GITHUB_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
