name: Publish Native Component List Website
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/web.yml
      - yarn.lock
      - apps/**
      - packages/**
      # Ignore Expo CLI for now...
      - '!packages/@expo/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: â¬¢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.17'
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
          git-lfs: 'true'
      - name: ðŸšš Pull Git LFS files
        run: git lfs pull

      #  Setup Expo CLI action
      # - name: Setup Expo
      #   uses: expo/expo-github-action@v5
      #   with:
      #     expo-version: 3.x
      #     expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      #     expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      #     expo-cache: true

      - name: ðŸ§¶ Install workspace node modules
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ðŸ”§ Install Expo CLI v3
        run: yarn global add expo-cli@3

      # - name: Publish Expo app
      #   working-directory: ./apps/native-component-list
      #   run: expo publish --release-channel=pr-${{ github.event.number }}
      # # Get Expo link for the comment
      # - name: Get expo link
      #   id: expo
      #   run: echo "::set-output name=path::@community/native-component-list?release-channel=pr-${{ github.event.number }}"

      - name: ðŸ—ï¸ Build the NCL website
        working-directory: ./apps/native-component-list
        run: yarn build:web
      - name: ðŸŒ Publish NCL website
        working-directory: ./apps/native-component-list
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          BUILD_ID: ${{ github.sha }}
        run: npx now deploy web-build --env NODE_ENV=production --confirm --public --no-clipboard --token=${ZEIT_TOKEN} > deploy-url.txt
      - name: âž• Add deploy url to GITHUB_ENV
        run: echo "ZEIT_DEPLOY=$(cat deploy-url.txt)" >> $GITHUB_ENV

      # Alias the now deployment URL
      #
      # NOTE(brentvatne): this is currently disabled because aliasing is failing with:
      #   "Error! The alias expo-web.now.sh is a deployment URL or it's in use by a different team."
      #
      # - name: Alias with PR number
      #   working-directory: ./apps/native-component-list
      #   env:
      #     ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      #     SITE_ALIAS: expo-web.now.sh
      #   run: npx now alias --token=${ZEIT_TOKEN} `cat deploy-url.txt` $SITE_ALIAS
