# Github workflows need to exist on the 'main' branch
# in order to be run on other branches using workflow_dispatch.
# The actual workflow is loaded from the target branch
# (the one we dispatch the workflow to run on)
# so we need a minimal failing job on main just to be able
# to trigger the workflow on other (usually sdk-xx) branches
name: iOS Shell App

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'type "upload" to confirm upload to S3'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Fail workflow
        run: |
          echo "Shell apps were dropped on 'main'. " \
          "Did you forget to select the SDK release branch when dispatching workflow?"
          exit 1
