name: E2E Test Suite for Expo Brownfield

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/test-suite-brownfield-isolated.yml
      - apps/brownfield-tester/expo-app/**
      - packages/expo-brownfield/**
  pull_request:
    paths:
      - .github/workflows/test-suite-brownfield-isolated.yml
      - apps/brownfield-tester/expo-app/**
      - packages/expo-brownfield/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-platform-for-e2e:
    runs-on: ubuntu-24.04
    outputs:
      should_run_ios: ${{ steps.changes.outputs.should_run_ios }}
      should_run_android: ${{ steps.changes.outputs.should_run_android }}
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v5
      - name: ðŸ§ Detect platform change
        id: changes
        uses: ./.github/actions/detect-platform-change
        with:
          android-paths: >-
            "packages/expo-brownfield/android/**",
            "packages/expo-brownfield/gradle-plugins/**"

          ios-paths: >-
            "packages/expo-brownfield/ios/**"

          common-paths: >-
            .github/workflows/test-suite-brownfield-isolated.yml,
            "apps/brownfield-tester/expo-app/**",
            "packages/expo-brownfield/cli/**",
            "packages/expo-brownfield/plugin/**",
            "packages/expo-brownfield/src/**",
            "packages/expo-brownfield/e2e/maestro/**"

  android-e2e:
    runs-on: ubuntu-24.04
    needs: detect-platform-for-e2e
    if: needs.detect-platform-for-e2e.outputs.should_run_android == 'true'
    strategy:
      matrix:
        api-level: [36]
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v5
      - name: ðŸ§¹ Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: ðŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: ðŸ”¨ Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: âž• Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: 'true'
          yarn-workspace: 'true'
          yarn-tools: 'true'
          react-native-gradle-downloads: 'true'
      - name: ðŸ§¶ Install workspace node modules
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ðŸ¤– Build and publish Android artifacts (apps/brownfield-tester/expo-app)
        run: |
          npx expo prebuild --clean -p android
          npx expo-brownfield build:android --repo MavenLocal --verbose
        working-directory: apps/brownfield-tester/expo-app
      - name: ðŸº Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: ðŸ§ª Run e2e tests (isolated brownfield)
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: |
            cd apps/brownfield-tester/android-integrated && \
            ./gradlew clean && \
            ./gradlew installRelease --refresh-dependencies
            cd ../../packages/expo-brownfield/e2e && \
            maestro test maestro/__tests__/android
      - name: ðŸ”” Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_android }}
          channel: '#expo-android'
          author_name: E2E Test Suite for Expo Brownfield

  # TODO(pmleczek): Add iOS job
  # ios-e2e:
