name: Test Suite Isolated Brownfield

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/test-suite-isolated-brownfield.yml
      - apps/minimal-tester/**
      - packages/expo/**
      - packages/expo-brownfield/**
      - packages/expo-modules-core/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # TODO(patrykml): Re-enable
  # ios-build:
  #   runs-on: macos-15
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       build-type: [debug, release]
  #   steps:
  #     - name: ðŸ‘€ Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: ðŸ”¨ Switch to Xcode 26.0
  #       run: sudo xcode-select --switch /Applications/Xcode_26.0.app
  #     - name: âž• Add `bin` to GITHUB_PATH
  #       run: echo "$(pwd)/bin" >> $GITHUB_PATH
  #     - name: ðŸ’Ž Setup Ruby and install gems
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true
  #         ruby-version: 3.2.2
  #     - name: â™»ï¸ Restore caches
  #       uses: ./.github/actions/expo-caches
  #       id: expo-caches
  #       with:
  #         yarn-workspace: "true"
  #         yarn-tools: "true"
  #     - name: ðŸ§¶ Install node modules in root dir
  #       if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
  #       run: yarn install --frozen-lockfile
  #     - name: ðŸ Build iOS artifacts
  #       working-directory: ./apps/minimal-tester
  #       run: |
  #         npx expo prebuild --clean --platform ios
  #         npx expo-brownfield build-ios --${{ matrix.build-type }} --verbose
  #       shell: bash
  #       env:
  #         NODE_ENV: production
  #     - name: ðŸ§¹ Cleanup unused simulator runtimes
  #       run: |
  #         xcrun simctl list devices -j | jq -r '.devices | to_entries[] | select(.key | contains("iOS") | not) | .value[].udid' | xargs -r -n1 xcrun simctl delete
  #         xcrun simctl list devices --json
  #         xcrun simctl erase all
  #         xcrun simctl shutdown all
  #         sudo xcodebuild -runFirstLaunch
  #     - name: ðŸº Install Maestro
  #       run: |
  #         curl -Ls "https://get.maestro.mobile.dev" | bash
  #         echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
  #     - name: ðŸ§ª Run e2e tests (isolated brownfield)
  #       run: ./setup/run-e2e-tests-ios.sh
  #       working-directory: packages/expo-brownfield/e2e
  #       env:
  #         MAESTRO_CLI_NO_ANALYTICS: 1
  #       timeout-minutes: 40
  #     - name: ðŸ“¸ Store testing artifacts
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       id: upload-artifacts
  #       with:
  #         name: isolated-brownfield-artifacts-ios
  #         path: |
  #           ~/.maestro/tests/**/*
  #           ~/Library/Logs/maestro/**/*
  #         overwrite: true
  #         include-hidden-files: true # .maestro is skipped otherwise
  #     - name: ðŸ”— Artifacts download URL
  #       if: always()
  #       run: |
  #         echo "Artifacts URL: ${{ steps.upload-artifacts.outputs.artifact-url }}"
  #     - name: ðŸ”” Notify on Slack
  #       uses: ./.github/actions/slack-notify
  #       if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
  #       with:
  #         webhook: ${{ secrets.slack_webhook_ios }}
  #         channel: "#expo-ios"
  #         author_name: Isolated Brownfield Test Suite (iOS)

  android-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [36]
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
    steps:
      - name: ðŸ‘€ Checkout
        uses: actions/checkout@v5
      - name: ðŸ§¹ Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: ðŸš€ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: ðŸ”¨ Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: "true"
          yarn-workspace: "true"
          yarn-tools: "true"
          react-native-gradle-downloads: "true"
      - name: ðŸ§¶ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ðŸ¤– Build and publish Android artifacts
        run: |
          npx expo prebuild --clean --platform android
          npx expo-brownfield build:android --repo MavenLocal --all --verbose
        shell: bash
        working-directory: ./apps/minimal-tester
        env:
          NODE_ENV: production
      - name: ðŸº Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: ðŸ§ª Run e2e tests (isolated brownfield)
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: |
            ./setup/run-e2e-tests-android.sh
          working-directory: packages/expo-brownfield/e2e
      - name: ðŸ”” Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_android }}
          channel: "#expo-android"
          author_name: Isolated Brownfield Test Suite (Android)
