name: Test Suite Brownfield

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/test-suite-brownfield.yml
      - apps/brownfield-tester/**
      - packages/expo/**
      - packages/expo-modules-core/**
      - packages/expo-dev-client/**
      - packages/expo-updates/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-build:
    strategy:
      fail-fast: true
      matrix:
        build-type: [debug, release]
    runs-on: macos-15
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: üî® Switch to Xcode 26.0
        run: sudo xcode-select --switch /Applications/Xcode_26.0.app
      - name: ‚ûï Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: üíé Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      - name: ‚ôªÔ∏è Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: "true"
          yarn-tools: "true"
      - name: üß∂ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: üçè Build iOS Project
        working-directory: ./apps/brownfield-tester
        run: |
          pod install --project-directory=ios
          xcodebuild -workspace ios/BrownfieldTester.xcworkspace -scheme BrownfieldTester -configuration $CONFIGURATION -sdk iphonesimulator -derivedDataPath "ios/build" | xcpretty
        shell: bash
        env:
          NODE_ENV: production
          CONFIGURATION: ${{ matrix.build-type == 'release' && 'Release' || 'Debug' }}
      - name: üì∏ Upload builds
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' && matrix.build-type == 'release' }} # Only archive release builds
        with:
          name: ios-builds-${{ matrix.build-type }}
          path: ${{ runner.temp }}/brownfield-tester/ios/build/**/BrownfieldTester.app/
      - name: üîî Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_ios }}
          channel: "#expo-ios"
          author_name: Brownfield Test Suite (iOS)
  android-build:
    strategy:
      fail-fast: true
      matrix:
        build-type: [debug, release]
    runs-on: ubuntu-24.04
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v5
      - name: üßπ Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: üöÄ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: üî® Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: ‚ôªÔ∏è Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: "true"
          yarn-workspace: "true"
          yarn-tools: "true"
          react-native-gradle-downloads: "true"
      - name: üß∂ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ü§ñ Build Android project
        run: |
          cd android && ./gradlew ":app:assemble$VARIANT"
        shell: bash
        working-directory: ./apps/brownfield-tester
        env:
          NODE_ENV: production
          VARIANT: ${{ matrix.build-type == 'release' && 'Release' || 'Debug' }}
      - name: üì∏ Upload builds
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' && matrix.build-type == 'release' }} # Only archive release builds
        with:
          name: android-builds-${{ matrix.build-type }}
          path: ./apps/brownfield-tester/android/app/build/outputs/apk/
      - name: üîî Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_android }}
          channel: "#expo-android"
          author_name: Brownfield Test Suite (Android)
