name: Updates CLI e2e

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/updates-e2e-cli.yml
      - packages/expo-updates/cli/**
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/updates-e2e-cli.yml
      - packages/expo-updates/cli/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v4
      - name: ‚¨¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ‚ûï Add `bin` to GITHUB_PATH
        run: echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: ‚ôªÔ∏è Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
      - name: üß∂ Yarn install
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: E2E Test expo-updates CLI
        run: yarn test:e2e-cli --ci --runInBand
        working-directory: packages/expo-updates
      - name: üîî Notify on Slack
        uses: 8398a7/action-slack@v3
        if: failure() && (github.event_name == 'schedule' || github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_api }}
        with:
          status: ${{ job.status }}
          fields: job,message,ref,eventName,author,took
          author_name: Updates CLI E2E
